apiVersion: skaffold/v1beta12
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: jenkinsxio/prow-pipeline-controller
  local: {}
profiles:
  - name: release
    build:
      cluster:
        pullSecret: /builder/home/kaniko-secret.json
      artifacts:
        - image: jenkinsxio/prow-pipeline-controller
          kaniko:
            image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
            buildContext:
              localDir: {}
    activation:
      - env: GOOGLE_APPLICATION_CREDENTIALS=/builder/home/kaniko-secret.json
